# Generated by Django 5.0.1 on 2024-02-01 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory', '0009_alter_dormitory_cost_per_month_and_more'),
        ('student', '0008_student_delete_basicinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField(auto_now_add=True)),
                ('date_of_checkin', models.DateField(default=None, null=True)),
                ('date_of_checkout', models.DateField(default=None, null=True)),
                ('number_of_days', models.IntegerField(default=0)),
                ('number_of_months', models.IntegerField(default=0)),
                ('number_of_seats', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('checkedin', 'Checked In'), ('checkedout', 'Checked Out')], default='booked', max_length=20)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'ordering': ['date_of_booking'],
            },
        ),
    ]
