# Generated by Django 5.0.1 on 2024-01-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory', '0007_alter_dormitory_dormitory_type'),
        ('student', '0003_alter_basicinformation_balance'),
        ('transaction', '0002_alter_transaction_balance_after_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField(auto_now_add=True)),
                ('date_of_checkin', models.DateField()),
                ('date_of_checkout', models.DateField()),
                ('number_of_days', models.IntegerField(default=0)),
                ('number_of_months', models.IntegerField(default=0)),
                ('number_of_seats', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('checkedin', 'Checked In'), ('checkedout', 'Checked Out')], default='booked', max_length=20)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.basicinformation')),
                ('transaction', models.ManyToManyField(to='transaction.transaction')),
            ],
            options={
                'ordering': ['date_of_booking'],
            },
        ),
    ]
