# Generated by Django 5.0.1 on 2024-01-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_checkin',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_of_checkout',
            field=models.DateField(default=None, null=True),
        ),
    ]
