# Generated by Django 5.0.1 on 2024-01-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='phone_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
