# Generated by Django 5.0.1 on 2024-01-15 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('image', models.ImageField(upload_to='student/media/images/')),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=6)),
                ('account_no', models.CharField(max_length=11)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University')], max_length=20)),
                ('institution_name', models.CharField(max_length=100)),
                ('institution_address', models.CharField(max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.basicinformation')),
            ],
        ),
    ]
