# Generated by Django 5.0.1 on 2024-01-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_basicinformation_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
