# Generated by Django 5.0.1 on 2024-01-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_basicinformation_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='institution_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='institution_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='institution_type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University')], default='university', max_length=20),
        ),
        migrations.DeleteModel(
            name='InstitutionInformation',
        ),
    ]
