# Generated by Django 5.0.1 on 2024-01-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_basicinformation_institution_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='account_no',
            field=models.CharField(editable=False, max_length=11, unique=True),
        ),
    ]
