# Generated by Django 5.0.1 on 2024-01-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_basicinformation_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='gender_type',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='institution_address',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='institution_type',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='street_address',
        ),
        migrations.AlterField(
            model_name='basicinformation',
            name='account_no',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='basicinformation',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
