# Generated by Django 5.0.1 on 2024-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='available_seats',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='cost_per_month',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='cost_per_night',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
