# Generated by Django 5.0.1 on 2024-01-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_alter_dormitory_available_seats_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dormitory',
        ),
    ]
