# Generated by Django 5.0.1 on 2024-01-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_delete_dormitory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dormitory/media/images')),
                ('dormitory_type', models.CharField(choices=[('ladies', 'Ladies'), ('boys', 'Boys')], max_length=10)),
                ('facilities', models.CharField(choices=[('super', 'Super'), ('regular', 'Regular')], max_length=20)),
                ('cost_per_night', models.IntegerField(blank=True, default=0)),
                ('cost_per_month', models.IntegerField(blank=True, default=0)),
                ('available_seats', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.location')),
            ],
        ),
    ]
