# Generated by Django 5.0.1 on 2024-01-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0004_dormitory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormitory',
            old_name='dormitory',
            new_name='locations',
        ),
    ]
