# Generated by Django 5.0.1 on 2024-01-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_rename_dormitory_dormitory_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormitory',
            old_name='locations',
            new_name='location',
        ),
    ]
