# Generated by Django 5.0.1 on 2024-01-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0006_rename_locations_dormitory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='dormitory_type',
            field=models.CharField(choices=[('girls', 'Girls'), ('boys', 'Boys')], max_length=10),
        ),
    ]
