# Generated by Django 5.0.1 on 2024-01-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='cost_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='cost_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
